apiVersion: v1
kind: Service
metadata:
  name: innovatech-frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  selector:
    app: innovatech-frontend
  ports:
    - port: 80
      targetPort: 80
